---
title: "about.Rmd"
author: "Professor: Adeil Araújo"
date: "*Blog construído com R Markdown*"
output: html_document
---

---
title: "Bugs, histórias, Etc & tal"
---

## Sobre o autor do blog

Sou professor de Física da rede pública estadual do Ceará. Tenho mestrado em Ensino de Física (MNPEF) e nos últimos anos tenho me dedicado a escrever sobre programação. Em 2023 publiquei o livro [Julia com física: uma introdução](https://www.seduc.ce.gov.br/wp-content/uploads/sites/37/2023/09/Ebook-02-Julia-com-Fisica.pdf) e em 2024 lançarei o livro *Modelagem computacional com o Web VPython: Mecânica*. A iniciativa de começar a escrever este blog se deu pela necessidade de aprender a trabalhar com planilhas em R. Estou super motivado a começar essa viagem. Caso tenha interesse também mantenho outro blog [Julia com física](https://juliacomfisica.github.io/). Essas e outras produções estão listadas no [meu site pessoal](https://adeil83.github.io/).

## Referência para construção deste blog

Para construir este blog utilizei como referência o blog Live Free or Dichotomize [How to make an R Markdown website (with RStudio!)](https://livefreeordichotomize.com/posts/2017-08-08-how-to-make-an-rmarkdown-website/index.html) seguindo as intruções passo a passo você conseguirá construir seu blog com R Markdown também. Se quiser, é claro!

## Um pouco de história da liguagem R

A linguagem R, nasceu nos anos 90, mas se popularizou mesmo nos anos 2000 quando **R**oss Ihaka e **R**obert Gentleman, professores de estatítica da Nova Zelândia trouxeram ao púlico a primeira versão da linguagem. No livro *Utilizando a linguagem R: conceitos, manipulação, modelagem e elaboração de relatórios* a autora Luciene Ferreira conta que "*Talvez por conincidência, as iniciais do nome desses professores iniciam pela letra R, uma boa hipótese para terem nomeado a linguagem de R*"

Link para aquisição do livro na [Amazon](https://www.amazon.com.br/Utilizando-linguagem-manipula%C3%A7%C3%A3o-visualiza%C3%A7%C3%A3o-elabora%C3%A7%C3%A3o/dp/8550814423).

## Material para estudo

O **PET Estatística** da Universidade Federal do Ceará - UFC possui uma atividade com R nas escolas.

*"Nessa atividade desenvolvemos a prática da matemática básica e da estatística com o uso do programa computacional R nas escolas de ensino médio da rede pública de Fortaleza. Anualmente, os membros do PET Estatística entram em contato com escolas públicas da cidade objetivando a concordância para ministrar as aulas. Caso sua escola esteja interessada em marcar um minicurso do software R, entre em contato conosco"*

Na página do [PET Estatítica](https://sites.google.com/view/petestatisticaufc/atividades) você consegue baixar uma [apostila](https://drive.google.com/file/d/1koBbKSarTit1jUBt0jLrGnjF3TMLCu7s/view) de introdução à R para escolas.Visite!